spring:
  application:
    name: stackorflow
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
  datasource:
    url: jdbc:h2:mem:test
  h2:
    console:
      enabled: true
      path: /h2-console
springdoc:
  swagger-ui:
    use-root-path: true

